
export const ENUM = {
    CONNECTED_TO_DATABASE: 'CONNECTED_TO_DATABASE',
    NOT_CONNECTED_TO_DATABASE: 'NOT_CONNECTED_TO_DATABASE',
    ALREADY_CONNECTED_TO_DATABASE_BRO: 'ALREADY_CONNECTED_TO_DATABASE_BRO',
    ERROR_WITH_RUNNING_QUERY: "ERROR_WITH_RUNNING_QUERY",
    ERROR_RUNNING_QUERY_BECAUSE_NO_CONNECTION: "ERROR_RUNNING_QUERY_BECAUSE_NO_CONNECTION_TO_DATABASE",
    ERROR_CLOSING_CONNECTION_TO_DB: "ERROR_CLOSING_CONNECTION_TO_DB",
    SUCCESSFUL_CLOSE_OF_CONNECTION_TO_DB: "SUCCESSFUL_CLOSE_OF_CONNECTION_TO_DB",
    SUCCESSFUL_QUERY: "SUCCESSFUL_QUERY",
    DATABASE_CONNECTION_STATUS_DISCONNECTED: "disconnected",
    DATABASE_CONNECTION_STATUS_CONNECTED: "connected",
    DATABASE_CONNECTION_STATUS_AUTHENTICATED: "authenticated",
    DATABASE_CONNECTION_ALREADY_CLOSED_BRO: "DATABASE_CONNECTION_ALREADY_CLOSED_BRO"
    
  };


